name: Update Openapi

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'openapi/openapi.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Auto Update OpenApi file
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update OpenApi and Swagger files
        run: |
          sh ./openapi/generate_openapi.sh

      - name: Commit & Push changes
        run: |
          git config --global user.name 'pagopa-github-bot' 
          git config --global user.email 'github-bot@pagopa.it'
          git add -A
          git commit -m "Auto Update Openapi and Swagger" || true
          git push
